# BuyMagicPlus Configuration
# By dmulloy2

# Debug
debug: false

# List of available packages
# Format: 
#  [packageName]:
#    - "<type>:<dat>, <amount>, <enchantment>:<level>..."
packages:
  "stone":
    - "1:0, 5"